runtime: nodejs20  # Node.js seçimi

instance_class: F4  # Uygulamanın performans seviyesini belirleyebilirsiniz

env_variables:
  NODE_ENV: "production"  # Üretim ortamı

handlers:
  - url: /static
    static_dir: build/static
  - url: /
    static_files: build/index.html
    upload: build/index.html